from app.models.context import ImplementationContext
from app.models.validation import ContextValidationResult


def assemble_markdown(
    context: ImplementationContext,
    validation: ContextValidationResult,
) -> str:

    if not validation.valid:
        raise ValueError(
            "Cannot assemble invalid implementation context."
        )

    sections = []

    # ---------------------------------------------------------
    # Header
    # ---------------------------------------------------------

    sections.append(
        f"""# {context.project_title}

## AI Coding Agent Project Context

> Generated by ContextForge AI

---
"""
    )

    # ---------------------------------------------------------
    # Project Overview
    # ---------------------------------------------------------

    sections.append(
        f"""# 1. Project Overview

## Project Summary

{context.project_summary}

## Problem

{context.problem}

## Target Users

{_bullet_list(context.target_users)}
"""
    )

    # ---------------------------------------------------------
    # Functional Requirements
    # ---------------------------------------------------------

    sections.append(
        f"""# 2. Functional Requirements

{_numbered_list(context.functional_requirements)}
"""
    )

    # ---------------------------------------------------------
    # Non Functional Requirements
    # ---------------------------------------------------------

    sections.append(
        f"""# 3. Non-Functional Requirements

{_numbered_list(context.non_functional_requirements)}
"""
    )

    # ---------------------------------------------------------
    # Architecture
    # ---------------------------------------------------------

    sections.append(
        f"""# 4. Architecture

{context.architecture_summary}
"""
    )

    # ---------------------------------------------------------
    # Technology Stack
    # ---------------------------------------------------------

    sections.append(
        f"""# 5. Technology Stack

{_bullet_list(context.technology_stack)}
"""
    )

    # ---------------------------------------------------------
    # Data Model
    # ---------------------------------------------------------

    sections.append(
        f"""# 6. Data Model

{_bullet_list(context.data_model)}
"""
    )

    # ---------------------------------------------------------
    # API Contract
    # ---------------------------------------------------------

    sections.append(
        f"""# 7. API Contract

{_bullet_list(context.api_contract)}
"""
    )

    # ---------------------------------------------------------
    # Security
    # ---------------------------------------------------------

    sections.append(
        f"""# 8. Security Requirements

{_bullet_list(context.security_requirements)}
"""
    )

    # ---------------------------------------------------------
    # Implementation Phases
    # ---------------------------------------------------------

    phases = []

    for phase in context.implementation_phases:

        phases.append(
            f"""## Phase {phase.phase} — {phase.name}

### Objective

{phase.objective}

### Tasks

{_bullet_list(phase.tasks)}

### Deliverables

{_bullet_list(phase.deliverables)}
"""
        )

    sections.append(
        "# 9. Implementation Plan\n\n"
        + "\n".join(phases)
    )

    # ---------------------------------------------------------
    # Agent Rules
    # ---------------------------------------------------------

    rules = []

    for index, rule in enumerate(
        context.agent_rules,
        start=1,
    ):
        rules.append(
            f"{index}. **{rule.category}:** {rule.rule}"
        )

    sections.append(
        "# 10. AI Coding Agent Rules\n\n"
        + "\n".join(rules)
    )

    # ---------------------------------------------------------
    # Definition of Done
    # ---------------------------------------------------------

    sections.append(
        f"""# 11. Definition of Done

{_checkbox_list(context.definition_of_done)}
"""
    )

    # ---------------------------------------------------------
    # Final Agent Instructions
    # ---------------------------------------------------------

    sections.append(
        """# 12. Final Instructions to the AI Coding Agent

You are responsible for implementing the project described in this
document.

Follow the architecture, technology stack, requirements, security
rules, implementation phases, and agent rules defined above.

Do not replace technologies or introduce unnecessary architecture
without a clear technical reason.

Implement the project incrementally.

After completing each implementation phase:

1. Verify the implementation.
2. Run appropriate tests.
3. Fix errors before continuing.
4. Confirm that the phase deliverables are complete.

The final implementation must satisfy the Definition of Done.
"""
    )

    return "\n\n".join(sections)


def _bullet_list(items: list[str]) -> str:

    if not items:
        return "- None specified."

    return "\n".join(
        f"- {item}"
        for item in items
    )


def _numbered_list(items: list[str]) -> str:

    if not items:
        return "No requirements specified."

    return "\n".join(
        f"{index}. {item}"
        for index, item in enumerate(
            items,
            start=1,
        )
    )


def _checkbox_list(items: list[str]) -> str:

    if not items:
        return "- [ ] None specified."

    return "\n".join(
        f"- [ ] {item}"
        for item in items
    )
